### ISSUE TITLE
Add support to co-authors

### ISSUE THREAD

**Issue by andre-filho** [andre-filho/commit-helper#6]
## Tasks
- [ ]  confirmation of 'do you have any co-authors? (y/N)'
- [ ] default must be 'no'
- [ ] if confirmation is a success, take name and email of co-authors formatting a string

**Comment by andre-filho** [comment]
this can be a little bit complicated
